
package co.edu.upb.nominae.extractor;

/**
 *
 * @author 000329745 Juan Camilo Villa 
 * @since 01/09/2021
 * @version 1.0
 * 
 * CONSTANTES CON QUERYES PARA LLENADO DE OBJETOS DESDE BASE DE DATOS
 */
public class Queries {
    
    public static final String NOMINA_QUERY = "SELECT HZRNNOM_PREFIJO, HZRNNOM_TIPO_DOC, HZRNNOM_CUNE_INTERNO, HZRNNOM_ANO, HZRNNOM_CONSECUTIVO_DOC, HZRNNOM_MES, HZRNNOM_FECHA_EXT, HZRNNOM_ESTADO FROM UPB_NOMINAE.HZRNNOM WHERE HZRNNOM_CUNE_INTERNO = ?";
    
    //public static final String HZRNTIP_QUERY = "";
    
    public static final String HZRNENC_QUERY = "SELECT HZRNENC_CUNE_INTERNO, HZRNENC_TIPO_DOC, to_char(HZRNENC_FECHA_ING,'yyyy-MM-dd') HZRNENC_FECHA_ING,to_char(HZRNENC_FECHA_RET,'yyyy-MM-dd') HZRNENC_FECHA_RET, to_char(HZRNENC_FECHA_LIQ_INI,'yyyy-MM-dd') HZRNENC_FECHA_LIQ_INI, to_char(HZRNENC_FECHA_LIQ_FIN,'yyyy-MM-dd') HZRNENC_FECHA_LIQ_FIN, HZRNENC_TIEMPO_LAB, to_char(HZRNENC_FECHA_EMISION,'yyyy-MM-dd') HZRNENC_FECHA_EMISION, HZRNENC_CODIGO_TRAB, HZRNENC_PREFIJO, HZRNENC_CONSECUTIVO, HZRNENC_NUMERO, HZRNENC_PAIS, HZRNENC_DEPART_ESTADO, HZRNENC_MUNICIPIO_CIUDAD, HZRNENC_IDIOMA, HZRNENC_VERSION, HZRNENC_AMBIENTE, HZRNENC_TIPO_XML, HZRNENC_CUNE, to_char(HZRNENC_FECHA_GENERA,'yyyy-MM-dd') HZRNENC_FECHA_GENERA, HZRNENC_HORA_GENERA, HZRNENC_PERIODO_NOM, HZRNENC_TIPO_MONEDA, HZRNENC_TRM, HZRNENC_NUM_PRED, HZRNENC_CUNE_PRED, to_char(HZRNENC_FECHA_GEN_PRED,'yyyy-MM-dd') HZRNENC_FECHA_GEN_PRED FROM UPB_NOMINAE.HZRNENC WHERE HZRNENC_CUNE_INTERNO = ?";
    
    public static final String HZRNNOV_QUERY = "SELECT HZRNNOV_CUNE_INTERNO, HZRNNOV_NOVEDAD, HZRNNOV_CUNE_NOV FROM UPB_NOMINAE.HZRNNOV  WHERE HZRNNOV_CUNE_INTERNO = ?";
               
    public static final String HZRNNOT_QUERY = "SELECT HZRNNOT_CUNE_INTERNO, HZRNNOT_NOTAS FROM UPB_NOMINAE.HZRNNOT WHERE HZRNNOT_CUNE_INTERNO = ?" ;

    public static final String HZRNEMI_QUERY = "SELECT HZRNEMI_CUNE_INTERNO, HZRNEMI_RAZON_SOCIAL, HZRNEMI_PRIMER_APELLIDO,HZRNEMI_SEGUNDO_APELLIDO, HZRNEMI_PRIMER_NOMBRE, HZRNEMI_OTROS_NOMBRES,HZRNEMI_NIT, HZRNEMI_DV, HZRNEMI_PAIS, HZRNEMI_DEPART_ESTADO, HZRNEMI_MUNICIPIO_CIUDAD, HZRNEMI_DIRECCION FROM UPB_NOMINAE.HZRNEMI WHERE HZRNEMI_CUNE_INTERNO = ?";
    
    public static final String HZRNREC_QUERY = "SELECT HZRNREC_CUNE_INTERNO, HZRNREC_TIPO_TRABAJADOR, HZRNREC_SUB_TIPO_TRABAJ, HZRNREC_ALTO_RIESGO_PENS, HZRNREC_TIPO_DOC, HZRNREC_NUM_DOC,HZRNREC_PRIMER_APELLIDO, HZRNREC_SEGUNDO_APELLIDO, HZRNREC_PRIMER_NOMBRE, HZRNREC_OTROS_NOMBRES, HZRNREC_LUGAR_TRAB_PAIS, HZRNREC_LUGAR_TRAB_DEPT_EST, HZRNREC_LUGAR_TRAB_MUN_CIUD, HZRNREC_LUGAR_TRAB_DIREC, HZRNREC_SALARIO_INTEGRAL, HZRNREC_TIPO_CONTRATO, HZRNREC_SUELDO, HZRNREC_COD_TRABAJADOR FROM UPB_NOMINAE.HZRNREC WHERE HZRNREC_CUNE_INTERNO = ?" ;

    public static final String HZRNPAG_QUERY = "SELECT HZRNPAG_CUNE_INTERNO, HZRNPAG_FORMA_PAGO, HZRNPAG_METODO_PAGO,HZRNPAG_BANCO, HZRNPAG_TIPO_CUENTA, HZRNPAG_NUM_CUENTA FROM UPB_NOMINAE.HZRNPAG WHERE HZRNPAG_CUNE_INTERNO = ?";
                
    public static final String HZRNFEP_QUERY = "SELECT HZRNFEP_CUNE_INTERNO, HZRNFEP_FECHA_PAGO FROM UPB_NOMINAE.HZRNFEP  WHERE HZRNFEP_CUNE_INTERNO = ?";

    public static final String HZRNITE_QUERY = "SELECT HZRNITE_CUNE_INTERNO, HZRNITE_DIAS_TRAB, HZRNITE_SUELDO_TRAB, HZRNITE_ID FROM UPB_NOMINAE.HZRNITE WHERE HZRNITE_CUNE_INTERNO = ?";
    
    public static final String HZRNETR_QUERY = "SELECT HZRNETR_AUX_TRANSPORTE, HZRNETR_VIAT_MANUT_SALARIAL, HZRNETR_VIAT_MANUT_NO_SALARIAL, HZRNETR_ITE_ID FROM UPB_NOMINAE.HZRNETR WHERE HZRNETR_ITE_ID = ?";

    public static final String HZRNEHE_QUERY = "SELECT HZRNEHE_HORAS_EXTRA, HZRNEHE_HORA_INICIO, HZRNEHE_HORA_FIN,HZRNEHE_CANTIDAD, HZRNEHE_PORCENTAJE, HZRNEHE_PAGO,HZRNEHE_ITE_ID FROM UPB_NOMINAE.HZRNEHE WHERE HZRNEHE_ITE_ID = ?";

    public static final String HZRNEVC_QUERY = "SELECT HZRNEVC_FECHA_INICIO, HZRNEVC_FECHA_FIN, HZRNEVC_CANTIDAD,HZRNEVC_PAGO, HZRNEVC_ITE_ID FROM UPB_NOMINAE.HZRNEVC WHERE HZRNEVC_ITE_ID = ?";
               
    public static final String HZRNEVA_QUERY = "SELECT HZRNEVA_CANTIDAD, HZRNEVA_PAGO, HZRNEVA_ITE_ID FROM UPB_NOMINAE.HZRNEVA WHERE HZRNEVA_ITE_ID = ?";
                
    public static final String HZRNEPR_QUERY = "SELECT HZRNEPR_CANTIDAD, HZRNEPR_PAGO, HZRNEPR_PAGONS,HZRNEPR_ITE_ID FROM UPB_NOMINAE.HZRNEPR WHERE HZRNEPR_ITE_ID = ?";
                
    public static final String HZRNECE_QUERY = "SELECT HZRNECE_PAGO, HZRNECE_PORCENTAJE, HZRNECE_PAGO_INTERESES,HZRNECE_ITE_ID FROM UPB_NOMINAE.HZRNECE WHERE HZRNECE_ITE_ID = ?";
               
    public static final String HZRNEIN_QUERY = "SELECT HZRNEIN_FECHA_INICIO, HZRNEIN_FECHA_FIN, HZRNEIN_CANTIDAD, HZRNEIN_TIPO, HZRNEIN_PAGO, HZRNEIN_ITE_ID FROM UPB_NOMINAE.HZRNEIN WHERE HZRNEIN_ITE_ID = ?";

    public static final String HZRNELI_QUERY = "SELECT HZRNELI_FECHA_INICIO, HZRNELI_FECHA_FIN, HZRNELI_CANTIDAD, HZRNELI_PAGO, HZRNELI_ITE_ID FROM UPB_NOMINAE.HZRNELI WHERE HZRNELI_ITE_ID = ?";

    public static final String HZRNELR_QUERY = "SELECT HZRNELR_FECHA_INICIO, HZRNELR_FECHA_FIN, HZRNELR_CANTIDAD,HZRNELR_PAGO, HZRNELR_ITE_ID FROM UPB_NOMINAE.HZRNELR WHERE HZRNELR_ITE_ID = ?";

    public static final String HZRNELN_QUERY = "SELECT HZRNELN_FECHA_INICIO, HZRNELN_FECHA_FIN, HZRNELN_CANTIDAD,HZRNELN_ITE_ID FROM UPB_NOMINAE.HZRNELN  WHERE HZRNELN_ITE_ID = ?";

    public static final String HZRNEBN_QUERY = "SELECT HZRNEBN_BONI_SALARIAL, HZRNEBN_BONI_NO_SALARIAL, HZRNEBN_ITE_ID FROM UPB_NOMINAE.HZRNEBN WHERE HZRNEBN_ITE_ID = ?";
  
    public static final String HZRNEAX_QUERY = "SELECT HZRNEAX_AUX_SALARIAL, HZRNEAX_AUX_NO_SALARIAL, HZRNEAX_ITE_ID FROM UPB_NOMINAE.HZRNEAX WHERE HZRNEAX_ITE_ID = ?";

    //NO SE EMITIRA POR PARTE DE LA UPB
    //public static final String HZRNEHL_QUERY = "SELECT HZRNEHL_FECHA_INICIO, HZRNEHL_FECHA_FIN, HZRNEHL_CANTIDAD, HZRNEHL_ITE_ID FROM UPB_NOMINAE.HZRNEHL WHERE HZRNEHL_ITE_ID = ?"; 

    public static final String HZRNEOT_QUERY = "SELECT HZRNEOT_DESC_CONCEPTO, HZRNEOT_CONCEP_SALARIAL, HZRNEOT_CONCEP_NO_SALARIAL,HZRNEOT_ITE_ID FROM UPB_NOMINAE.HZRNEOT WHERE HZRNEOT_ITE_ID = ?";
 
    public static final String HZRNECM_QUERY = "SELECT HZRNECM_COMPENS_ORDINARIA, HZRNECM_COMPENS_EXTRAORDINARIA, HZRNECM_ITE_ID FROM UPB_NOMINAE.HZRNECM WHERE HZRNECM_ITE_ID = ?";

    //NO SE EMITIRA POR PARTE DE LA UPB
    //public static final String HZRNEBO_QUERY = "SELECT HZRNEBO_PAGO_SALARIAL, HZRNEBO_PAGO_NO_SALARIAL, HZRNEBO_PAGO_ALIMENT_SALARIAL,HZRNEBO_PAGO_ALIMENT_NO_SALARY, HZRNEBO_ITE_ID FROM UPB_NOMINAE.HZRN  WHERE HZRNEBO_ITE_ID = ?"; 
   
    public static final String HZRNECO_QUERY = "SELECT HZRNECO_COMISION, HZRNECO_PAGO_TERCERO, HZRNECO_ANTICIPOS_NOMINA,HZRNECO_ITE_ID FROM UPB_NOMINAE.HZRNECO WHERE HZRNECO_ITE_ID = ?";
  
    public static final String HZRNEVO_QUERY = "SELECT HZRNEVO_DOTACION, HZRNEVO_APOYO_SOSTENIMIENT, HZRNEVO_TELETRABAJO,HZRNEVO_BONIF_RETIRO, HZRNEVO_INDEMNIZACION, HZRNEVO_REINTEGRO,HZRNEVO_ITE_ID FROM UPB_NOMINAE.HZRNEVO WHERE HZRNEVO_ITE_ID = ?";
   
    public static final String HZRNITS_QUERY = "SELECT HZRNITS_CUNE_INTERNO, HZRNITS_PORCENTAJE, HZRNITS_DEDUCCION,HZRNITS_ID FROM UPB_NOMINAE.HZRNITS WHERE HZRNITS_CUNE_INTERNO = ?";

    public static final String HZRNSPE_QUERY = "SELECT HZRNSPE_PORCENTAJE, HZRNSPE_DEDUCCION, HZRNSPE_ITS_ID FROM UPB_NOMINAE.HZRNSPE WHERE HZRNSPE_ITS_ID = ?";

    public static final String HZRNSSP_QUERY = "SELECT HZRNSSP_PORCENTAJE, HZRNSSP_DEDUC_SEG_PENSIONAL, HZRNSSP_PORCENTAJE_SUBSISTEN,HZRNSSP_DEDUC_SUBSISTEN, HZRNSSP_ITS_ID FROM UPB_NOMINAE.HZRNSSP  WHERE HZRNSSP_ITS_ID = ?";
   
    public static final String HZRNSIN_QUERY = "SELECT HZRNSIN_PORCENTAJE, HZRNSIN_DEDUCCION, HZRNSIN_ITS_ID FROM UPB_NOMINAE.HZRNSIN WHERE HZRNSIN_ITS_ID = ?";
 
    //NO SE EMITIRA POR PARTE DE LA UPB
    //public static final String HZRNSAN_QUERY = "SELECT HZRNSAN_SANCION_PUBLICA, HZRNSAN_SANCION_PRIVADA, HZRNSAN_ITS_ID FROM UPB_NOMINAE.HZRNSAN WHERE HZRNSAN_ITS_ID = ?"; 
    
    public static final String HZRNSLI_QUERY = "SELECT HZRNSLI_DESCRIPCION, HZRNSLI_DEDUCCION, HZRNSLI_ITS_ID FROM UPB_NOMINAE.HZRNSLI WHERE HZRNSLI_ITS_ID = ?";
    
    public static final String HZRNSOT_QUERY = "SELECT HZRNSOT_PAGO_TERCERO, HZRNSOT_ANTICIPO, HZRNSOT_OTRA_DEDUCCION,HZRNSOT_ITS_ID FROM UPB_NOMINAE.HZRNSOT WHERE HZRNSOT_ITS_ID = ?";
   
    public static final String HZRNSVA_QUERY = "SELECT HZRNSVA_PENSION_VOLUNTARIA, HZRNSVA_RENTENCION_FTE, HZRNSVA_AFC,HZRNSVA_COOPERATIVA, HZRNSVA_EMBARGO, HZRNSVA_PLAN_COMPLEMENT,HZRNSVA_EDUCACION, HZRNSVA_REINTEGRO, HZRNSVA_DEUDA, HZRNSVA_ITS_ID FROM UPB_NOMINAE.HZRNSVA  WHERE HZRNSVA_ITS_ID = ?";
   
    public static final String HZRNTOT_QUERY = "SELECT HZRNTOT_CUNE_INTERNO, HZRNTOT_REDONDEO, HZRNTOT_DEVENGADOS_TOTAL,HZRNTOT_DEDUCCIONES_TOTAL, HZRNTOT_COMPROBANTE_TOTAL FROM UPB_NOMINAE.HZRNTOT  WHERE HZRNTOT_CUNE_INTERNO = ?";
    
}
